import { IsString, IsOptional, IsPhoneNumber, IsDate, IsUUID } from 'class-validator';
import { Column } from 'typeorm';
// import { Role} from 'src/authroization/roles.decorator';
import { Roles } from 'src/authroization/roles.enum';

export class CreateUserDto {
 
  @IsOptional() // Optional if the userId is generated by the system
  userId?: number;

  @IsString()
  fname: string;

  @IsString()
  lname: string;

  @Column({ type: 'varchar', length: 255, unique: true })
  email: string; // Email address, unique in the system

  @Column({ type: 'varchar', length: 255 })
  password: string; // Hashed password for the user
  

  @Column({ type: 'enum', enum: Roles, default: Roles.Customer })
  role: Roles;

  @IsPhoneNumber(null) // Use specific locale if needed
  contactNumber: string;
}
