import { IsString, IsOptional, IsPhoneNumber, IsDate, IsUUID } from 'class-validator';
import { Column } from 'typeorm';

export class CreateUserDto {
 
  @IsOptional() // Optional if the userId is generated by the system
  userId?: number;

  @IsString()
  fname: string;

  @IsString()
  lname: string;

  @Column({ type: 'varchar', length: 255, unique: true })
  email: string; // Email address, unique in the system

  @Column({ type: 'varchar', length: 255 })
  password: string; // Hashed password for the user
  

  @IsPhoneNumber(null) // Use specific locale if needed
  contactNumber: string;

  @IsDate()
  @IsOptional() // Optional, as it may be auto-generated
  deletedAt?: Date;

  @IsDate()
  @IsOptional() // Optional, as it may be auto-generated
  createdAt?: Date;

  @IsDate()
  @IsOptional() // Optional, as it may be auto-generated
  updatedAt?: Date;
}
